

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: recipe_management
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe123
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent database storage
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user -d recipe_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      postgres:
        condition: service_healthy
    build: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recipe_management?sslmode=disable
      SPRING_DATASOURCE_USERNAME: recipe_user
      SPRING_DATASOURCE_PASSWORD: recipe123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
